config/routes.rb
Rails.application.routes.draw do

 resources :articles
 #root 'articles#index'
  resources :users
  root 'users#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_one_attached :avatar
	 belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article =  Article.all
    @article = Article.paginate(:page => params[:page], :per_page => 3)
  end


  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_parmas)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
     @article = Article.find(params[:id])
      if @article.update(article_parmas)
        redirect_to root_path
     else
        render :edit
     end    
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
       redirect_to root_path
    end  
  end
  
  private
  def article_parmas
   params.require(:article).permit(:title,:description,:avatar, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_parmas)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])

  end
  def update
    @user = User.find(params[:id])
     if @user.update(user_parmas)
        redirect_to root_path
     else
        render :edit
     end    
  end
  def destroy
    @user = User.find(user_parmas)
    if @user.destroy
      redirect_to root_path
    end
  end

  private
  def user_parmas
    params.require(:user).permit(:name,:phone,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="card" style="width: 18rem;">
  <%=form_with model: @article do |form|%>
   <div class="card-body">
    <h5 class="card-title">Aritcal Edit Form</h5>
       <p class="card-text">
         <%=form.label :title%>
         <%=form.text_field :title%><br>
         <%=form.label :description%>
         <%=form.text_field :description%> <br>
         <%= form.file_field :avatar %><br>
         <%=form.submit%>
        </p>
   </div>
  <%end%>
</div>

app/views/articles/index.html.erb
<h2> Dashboard </h2>
<div class="container">
   <%= link_to"AddArticale",new_article_path,class: "btn btn-primary" %>
   <div class="justify-content-center">
      <% @article.each do |art|%>
         <div class="card mb-3 m-auto m-0" style="width: 18rem;">
            <div class="card-body">
               <h5 class="card-title"><%=art.title%></h5>
               <p class="card-text"><%= h truncate(art.description, :length => 80) %></p>
               <%= link_to"Show",article_path(art.id),class: " btn btn-primary" %>
            </div>
         </div>
      <% end %>
      <div class="digg_pagination">
         <div class="page_info">
            <%= page_entries_info @article %>
         </div>
         <%= will_paginate @article, :container => false %>
      </div>
   </div>
</div>

app/views/articles/new.html.erb
<div class="container">
 <form>
    <%=form_with model: @article do |form|%>
           <div>
             <%=form.label :title%>
             <%=form.text_field :title%><br>
            </div>

            <div>
             <%=form.label :description%>
             <%=form.text_field :description%> <br>
            </div>

            <div>
              <%= form.file_field :avatar %><br>
            </div>

            <div>
             <%=form.label :UserId%>
             <%=form.text_field :user_id%> <br>
             </div>

           <%=form.submit "Submit",class: "btn btn-success"%>
          </p>
     </div>
    <%end%>
 </form>
</div>

app/views/articles/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <%=image_tag(@article.avatar,class: "IMG") if  @article.avatar.attached?%>
            <h5><%=@article.title%></h5>
            <p><%=@article.description%></p>
            <%=link_to"Edit Article",edit_article_path(@article),class:"btn btn-warning Btn"%>
            <%=link_to"Delete",article_path(@article), data: {
            method: :delete,
            confirm: "Are you sure?"
            },class:"btn btn-danger Btn"%>
            <%=link_to"Back",root_path(@article),class:"btn btn-secondary Btn"%>
        </div>
        <div class="col-sm-2"></div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="card text-white bg-info mb-3" style="max-width: 18rem;">
  <div class="card-header">Edit User </div>
  <div class="card-body">

    <h5 class="card-title"><%=form_with model: @user do |form|%>
</h5>
    <p class="card-text"><%=form.label :Name%></p>
    <p class="card-text"> <%=form.text_field :name%><br>
  </p>
    <p class="card-text"><%=form.label :phone%></p>
    <p class="card-text"> <%=form.text_field :phone%><br>
    </p>



  </div>


 <%=form.label :Eamil%>
 <%=form.text_field :email%><br>
<%=form.submit%>
<%end%>

app/views/users/index.html.erb
<div class="container">
  <%=link_to"Add User",new_user_path,class: "btn btn-primary"%>
  <%= link_to"Go to Article Dashboard",articles_path,class: "btn btn-info" %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Show</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
       <%@users.each do |f|%>
      <tr>
        <th scope="row"><%=f.id%></th>
        <td><%=f.name%></td>
        <td><%=f.phone%></td>
        <td><%=f.email%></td>
        <td><%=link_to"Show",user_path(f.id),class: " btn btn-primary"%></td>
        <td><%= link_to "Destroy", user_path(f), data: {
                      method: :delete,
                      confirm: "Are you sure?"
                    }, class: "btn btn-danger"%>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>  
<div>

app/views/users/new.html.erb
<div class="container">
    <form>
        <%=form_with model: @user do |form|%>
        <div class="form-group">
         <%=form.label :Name%>
         <%=form.text_field :name, class: "form-control"%><br>
        </div>

        <div>
         <%=form.label :Phone%>
         <%=form.text_field :phone, class: "form-control"%> <br>
        </div>

        <div>
         <%=form.label :Eamil%>
         <%=form.text_field :email, class:"form-control"%><br>
        </div>

        <%=form.submit%>
        <%end%>
    </form>
</div>

app/views/users/show.html.erb
<div  align="center">
<div class="card" style="width: 18rem;">
  <h5 class="card-header">Informantion  of User</h5>
  <div class="card-body">
    <h5 class="card-title">Name: <%= @user.name%><br>
    </h5>
    <p class="card-text">Email: <%= @user.email%><br>
    </p>
     <p class="card-text">Phone: <%= @user.phone%><br>
   <br>
 </p>

  <p class="card-text"><%=link_to"Edit User",edit_user_path(@user)%><br>
   <br>
 </p>
  </div>
</div>

</div>